---
AWSTemplateFormatVersion: '2010-09-09'
Description: EBS Volume
Parameters:
  AvailabilityZones:
    Description: Availability zone to deploy
    Type: String
    Default: us-east-1f
Resources:
  EBSVolume:    
    Type: "AWS::EC2::Volume"
    Properties:
      Encrypted: true
      AvailabilityZone: !Ref AvailabilityZones
      Size: 100
      Tags:
      - Key: Name
        Value: !Ref AWS::StackName    