---
AWSTemplateFormatVersion: '2010-09-09'
Description: Create a Secret
Resources:
  MySecretB:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Ref AWS::StackName
      Description: This secret has a hardcoded password in SecretString (use GenerateSecretString instead)
      SecretString: '{"username":"MasterUsername","password":"secret-password"}'
      Tags:
        -
          Key: AppName
          Value: AppB
Outputs:
  SecretName: 
    Value: !Sub ${MySecretB}
    Description: Name of the Secrets Manager Secrets used by RDS - used by a Python program to connect to RDS MySQL database