---
AWSTemplateFormatVersion: '2010-09-09'
Description: Test Import Value from Export Value
Parameters:
  ExportStackName:
    Type: String
    Default: "test"
Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Fn::ImportValue: !Sub '${ExportStackName}-us-east-1'