Parameters: 
  SSMParam: 
    Type: AWS::SSM::Parameter::Name 
    Description: Ensure this SSM Parameter exists
    Default: "ContinuousAssessmentInput" 
Resources:
  BasicParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "SiteBucketPipeline"
      Type: "String"
      Value: !Sub "${AWS::StackName}"
      Description: "SSM Parameter for running date command."
      
      
      